# This file may be used to create an environment using:
# $ conda env create -f environment.yml
# platform: linux-64
name: ucsc 
channels:
  - bioconda
  - conda-forge
dependencies:
  - python
  - filecache
